#Special configuration file to run tests on Travis-CI via GitHub notifications
#See http://travis-ci.org/ for details
#

language: python
python:
  - "3.5"

before_install:
  - "export PY3=yes"
  - "export PYPY=no"

install:
  - "sudo apt-get install libatlas-base-dev gfortran"
  - "travis_wait pip install scipy"
  - "pip install matplotlib"
  - "pip install coveralls"

script:
  - coverage run --source genomics setup.py test

after_success:
  - coveralls

